filter:
  excluded_paths:
    - 'tests/*'

checks:
  php: true

coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true

build:
  environment:
    php:
      version: 7

  tests:
    override:
      -
        command: './vendor/bin/phpunit --coverage-clover=coverage'
        coverage:
          file: 'coverage'
          format: 'clover'